config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/manifesto' , to: 'pages#manifesto'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def manifesto
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<div class="container">
<nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "TravelList", root_path, class:"navbar-brand"%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="link_nav_text"><%= link_to "Manifesto ", manifesto_path, class:"link_nav_text"%></li>
            <li class="link_nav"><%= link_to "Add a place ", root_path, class:"btn btn-danger btn-rounded btn-lg" %></li>


          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Siliconrun</title>
    <link rel="stylesheet"  href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
     <link href="https://fonts.googleapis.com/css?family=Roboto|Source+Sans+Pro" rel="stylesheet">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
     integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
     <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<section id="banner" data-blink-id="pvb1pxmp5cau7rq4c24yp" style="background-size: cover;background-position: center center;background-repeat: no-repeat;background-image: url(/travel_trip.jpg);">
 <div class="banner-text">
  <h2 class="description-header">THE WORLD IS WAITING FOR YOU </h2> <br>
  <h4>
Discover the most beautiful places for people who want to go around the world</h4>
 </div>
 <div class="dimmer"></div>
</section>

<div class="container">
  <div class="row">
    <div class="text-center">
      <h3 class="activite">... </h3>
      <p class="mission">"... " <br> Lahcen Sabari, fondateur du club</p>
    </div>
  </div>
</div>

app/views/pages/manifesto.html.erb
<h1>Pages#manifesto</h1>
<p>Find me in app/views/pages/manifesto.html.erb</p>